### ISSUE TITLE
tab组件，custom-class无法覆盖 van-tab--active 

### ISSUE THREAD

**Issue by javaSwing** [youzan/vant-weapp#1255]
**问题**
使用tab组件时，无法使用custom-class 来覆盖实现van-tab--active 样式，已经参考过[710](https://github.com/youzan/vant-weapp/issues/710)

**截图**
![image](https://user-images.githubusercontent.com/7713463/51827841-3b781b80-2325-11e9-8290-73fa8b9fdfb8.png)
```html
 <van-tabs custom-class="list" swipe-threshold="{{4}}" active="{{ 0 }}" bind:change="onChange">
    <van-tab title="全部" title-style="color:#666666"></van-tab>
    <van-tab title="标签 2" title-style="color:#666666"></van-tab>
    <van-tab title="标签 3" title-style="color:#666666"></van-tab>
    <van-tab title="标签 4" title-style="color:#666666"></van-tab>
    <van-tab title="标签 5" title-style="color:#666666"></van-tab>
    <van-tab title="标签 6" title-style="color:#666666"></van-tab>
    <van-tab title="标签 7" title-style="color:#666666"></van-tab>
  </van-tabs>
```
```css
.list {
  width: 85%;
  display: inline-block;
  overflow: hidden;
  z-index: 2;
}
.list .van-tab--active{
  font-weight:500;
  color:blue !important;
}
```

**环境**
 - 设备: 小程序开发模拟器
 - 基础库版本:  2.5.1
 - Vant Weapp 版本: 0.5.1
