### ISSUE TITLE
radio和checkbox后面的选项内容如果太长会导致排版变形

### ISSUE THREAD

**Issue by StarsMoon** [youzan/vant-weapp#1413]
![image](https://user-images.githubusercontent.com/9744637/54366950-86b77500-46ac-11e9-86e5-7ca9ffbe5f54.png)
如图，有什么解决办法吗？

**Comment by ZacharySun** [comment]
同样遇到这个问题，期待解决

**Comment by chenjiahan** [comment]
建议自行通过 `label-class` 增加最大宽度限制进行解决

```html
<van-checkbox label-class="custom-label" />
```

```css
.custom-label {
    max-width: 200px;
}
```
