### ISSUE TITLE
van-card thumb-class将图片缩小后，后面的文字怎么调整位置，紧跟图片

### ISSUE THREAD

**Issue by ArthurCL** [youzan/vant-weapp#2020]
.thumb-class {
  width: 20vw !important;
  height: 20vw !important;
}

**Comment by ArthurCL** [comment]
![1568182582462](https://user-images.githubusercontent.com/26400117/64672699-c1a13680-d49e-11e9-8775-13393c30e260.jpg)
wqe

**Comment by chenjiahan** [comment]
```html
<van-card custom-class="my-class" />
```

```css
.my-card .van-card__thumb {
  width: 20vw;
  height: 20vw;
}
```

这样写即可
