### ISSUE TITLE
Tab 在 iOS下的惯性滑动问题

### ISSUE THREAD

**Issue by yuerzm** [youzan/vant-weapp#2506]
解决 tab 在 iOS  下的惯性滑动问题
```css
/* @vant/weapp/tab/index.wxss */
.van-tab__pane {
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
}
```
