### ISSUE TITLE
[Bug Report] iphonese上Tabbar显示错位

### ISSUE THREAD

**Issue by argzs** [youzan/vant-weapp#2988]
### 设备
iPhone SE

### VantWeapp 版本
1.2.0

### 基础库版本
2.10.4

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/tabbar

### 描述问题
iPhone SE 上 Tabbar 显示错位，会偏上一些

**Comment by zaxlct** [comment]
![image](https://user-images.githubusercontent.com/14342431/78965026-6fa4ba00-7b2e-11ea-9645-8c3052d1f710.png)
v 1.2.0
phoneXR

**Comment by momodezou** [comment]
![image](https://user-images.githubusercontent.com/44139391/80566988-c06d4b80-8a26-11ea-8963-2040cb43e6ff.png)
上面差不多的问题，设置border后border就在tabbar中间，上面部分的背景颜色会挡不住
整个tabbar就像下面一样，只是里面的 内容流出了安全距离
![image](https://user-images.githubusercontent.com/44139391/80567329-7b95e480-8a27-11ea-8404-cca58cb1673c.png)

**Comment by imlooke** [comment]
![777668eaf3c3e14af7c9d085e26b00c3](https://user-images.githubusercontent.com/12030492/81527774-bdab1880-938d-11ea-9504-e25ce7f868ee.JPG)

已解决，因为tabbar高度是固定的，增加的padding-bottom并没有改变高度

增加以下代码即可解决
```css
.van-tabbar--safe {
  height: auto !important;
  min-height: 100rpx;
}

.van-tabbar--safe .van-tabbar-item {
  height: auto;
  padding: 13rpx 0;
}
```
