### ISSUE TITLE
[Bug Report] van-goods-action样式

### ISSUE THREAD

**Issue by 1sm23** [youzan/vant-weapp#3032]
### 设备
iPhone5

### VantWeapp 版本
1.2.0

### 基础库版本
2.10.4

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://i.loli.net/2020/04/17/MK3aQ54ynzVZNWp.png)

### 请提供核心代码片段链接
https://youzan.github.io/vant-weapp/#/goods-action

### 描述问题
van-goods-action的button 兼容iPhone5

**Comment by 1sm23** [comment]
暂时修改了`van-button`的样式处理了,但是又怕别的地方出问题
```css
.van-button__text{
display:inline;
line-height:1.2;
}
```
