### ISSUE TITLE
dropdown下拉框item设置font-size与color失效

### ISSUE THREAD

**Issue by hathawayssm** [youzan/vant-weapp#3073]
写在**dist/dropdown-item/index.wxss**文件最后，
```
 .van-dropdown-item__option{
    display: inline;
    text-align:left;
    /* font-style: italic; */
    font-size: 10px !important;
    color: inherit
  }
```
字体设置失效

行内样式popupStyle="font-size:10px;"同样失效，且只是font-size与color失效，font-weight等属性可以正常显示。

**Comment by rex-zsd** [comment]
这段代码是你自己加上去的？

**Comment by rex-zsd** [comment]
直接在 `.van-dropdown-item__option`上改样式是不会生效的，因为它是一个自定义组件。
可以给它设置CSS属性，比如
```css
.van-dropdown-item__option {
  --cell-font-size: 10px;
  --cell-text-color: inherit;
}
```
