### ISSUE TITLE
van-button 按钮组件文字大小样式设置无效

### ISSUE THREAD

**Issue by syq7970** [youzan/vant-weapp#3588]
微信sdk: 2.12.2
工具：微信开发者工具预览
vant-weapp: 1.5.0

不管是在app.wxss中
```css
.van-button--primary {
  font-size: 36rpx !important;
  background-color: #1dbcc9 !important;
  height: 80rpx !important;
}
```
还是使用custom-class设置font-size均无效。
