### ISSUE TITLE
sidebar 里的 active-class  设置border-color 始终不生效，设置的字体大小又可以。

### ISSUE THREAD

**Issue by spiritelf** [youzan/vant-weapp#3616]
```
<van-sidebar class="sidebar" custom-class="tag1">
  <view wx:for="{{navList}}" wx:for-item="item">
    <!-- 传递css变量  style=sidebar-selected-border-color:#3098d5 -->
    <van-sidebar-item title="{{item.name}}" bind:click="onSideBarClick" active-class="van-active-a" />
    <view class="sub-sidebar" bindtap="onSubBarClick" wx:if="{{item.checked}}" wx:for="{{item.subCategoryList}}" wx:for-item="subCategoryList" data-id="{{subCategoryList.id}}">
      <!-- <van-sidebar-item title="{{subCategoryList.name}}" /> -->
      <view class="sub-sidebar-dot"></view>
      <!-- 使用text始终不能居中对象 -->
      <view class="sub-sidebar-text  {{ currentCateId == subCategoryList.id ? 'active' : ''}}">
        {{subCategoryList.name}}
      </view>
    </view>
  </view>




.van-sidebar-item--selected.van-active-a view {
  color: #3098d5;
  font-weight: 500;
  border-color: #3098d5 !important;
  font-size: 14px;
}

```

**Comment by rex-zsd** [comment]
这里后面加了一个 view，导致样式没有应用上
```css
.van-sidebar-item--selected.van-active-a view {
  color: #3098d5;
  font-weight: 500;
  border-color: #3098d5 !important;
  font-size: 14px;
}
```

自定义激活态的边框颜色还有一个方法，可以直接在页面样式中设置 CSS 变量
```css
page {
  --sidebar-selected-border-color: #3098d5;
}
```
