### ISSUE TITLE
[Bug Report] van-popup和van-dropdown-menu配合有bug

### ISSUE THREAD

**Issue by lyj0309** [youzan/vant-weapp#3813]
### 设备
iphonex

### VantWeapp 版本
1.6.2

### 基础库版本
2.13.1

### 如果是 UI 问题，截图链接（多图回车分隔）

![截图](https://sm.ms/image/vYMn4JEiHLufhx1)

### 请提供核心代码片段链接
https://gist.github.com/lyj0309/650629892be85e1805217984a874155d

### 描述问题
van-popup和van-dropdown-menu配合使用，会有显示bug

**Comment by rex-zsd** [comment]
先说结论，组件库目前无法解决这个问题，但可以在外部通过覆盖样式的方式去解决。

如果是组件内使用了 popup 和 dropdown-menu

给组件解除样式隔离

```js
Component({
  options: {
    styleIsolation: 'shared',
  },
});
```

在组件样式内做覆盖

```css
.van-dropdown-item {
  top: 50px !important;
}
```

如果是页面内使用，直接在页面的 wxss 内加上覆盖样式即可

```css
.van-dropdown-item {
  top: 50px !important;
}
```
