### ISSUE TITLE
[Feature Request] Filed组件 能否添加属性来控制label中的空格显示方式？

### ISSUE THREAD

**Issue by echokh** [youzan/vant-weapp#3841]
### 这个功能解决了什么问题
目前，Field组件只会识别一个空格，添加属性来控制是否显示多个空格，对于界面排版的会有非常大的帮助

### 建议的API是什么样的
增加属性space 类型是boolean，选择是的时候可以自己控制空格的显示。不才看了下源码，在van-cell中的  <block wx:if="{{ title }}">{{ title }}</block>
 是否改可以改为text呢？

**Comment by rex-zsd** [comment]
有点没理解，是 `label` 文字还是输入框中的文字？

**Comment by echokh** [comment]
> 有点没理解，是 `label` 文字还是输入框中的文字？
`label` 文字，

**Comment by rex-zsd** [comment]
```html
<van-field label="姓    名" />
<van-field label="居住地" />
```

是这种场景吗？希望通过空格使几个 field 的 label 保持垂直一致？

**Comment by echokh** [comment]
> ```
> <van-field label="姓  名" />
> <van-field label="居住地" />
> ```
> 
> 是这种场景吗？希望通过空格使几个 field 的 label 保持垂直一致？

对的，完美get我的点

**Comment by rex-zsd** [comment]
其实对齐不用现有的外部样式类就可以实现了，不需要控制空格的行为

```html
<van-field label="姓名" label-class="my-label" />
<van-field label="居住地" label-class="my-label" />

```

```css
.my-label {
  text-align: justify;
  text-align-last: justify;
  -webkit-text-align-last: justify;
  width: 60px;
}
```
