### ISSUE TITLE
[Bug Report] van-image 组件使用【外部样式类】无效

### ISSUE THREAD

**Issue by jspao** [youzan/vant-weapp#5201]
### 重现链接

``` html
<van-image fit="cover" custom-class="van-image__avatar"  radius="5" width="50" height="50" src="https://img.yzcdn.cn/vant/cat.jpeg" />
```

``` css
.van-image__avatar {
border: 2px solid #fff
}
```

### Vant Weapp 版本

1.10.12

### 描述一下你遇到的问题。

uniapp + vue3 js版本 + vant 1.10.12 van-image 组件使用【外部样式类】无效

### 重现步骤

[Bug Report] van-image 组件使用【外部样式类】无效

### 设备/浏览器

hbuild / 微信开发者工具
