### ISSUE TITLE
[Feature Request] [dialog]希望增加dialog 组件底部按钮的可定制性

### ISSUE THREAD

**Issue by jiaqidegege** [youzan/vant-weapp#5425]
### 这个功能解决了什么问题？

增加dialog底部按钮的样式可定制性
1. [目前底部button的border优先级已经是`important!`无法修改,](https://github.com/youzan/vant-weapp/blob/ffb1fe605382c41798f59e267c405dfd55c8c73d/packages/dialog/index.less#LL84C1-L87C4) 建议改成css变量：

```css
&__confirm,
&__cancel {
    --button-border-width: 0px;
  }
```
2. 希望能将取消和确认按钮的custom-class暴露出来：
目前要想覆盖底部按钮样式，只能使用所有button共享的类名，比如`.van-button`，这会导致页面所有button都被影响

### 你期望的 API 是什么样子的？

暴露更多的外部样式类：
取消按钮的外部样式类： `van-dialog__cancel`
确认按钮的外部样式类：`van-dialog__confirm`
