### ISSUE TITLE
[Bug Report] Stepper真机下不显示加减号

### ISSUE THREAD

**Issue by lonffreytu** [youzan/vant-weapp#5821]
### 重现链接

<van-stepper value="{{ scale }}" min="0" max="2" step="0.5"/>

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

在Android设备上都无法显示stepper的加减号，是空白的。功能正常可用。但不显示“-” “+”
以下是真机显示效果
![2dabf744ef2fa750777326fd08e7177](https://github.com/youzan/vant-weapp/assets/110774929/0a004150-a64a-401d-b881-563fc8370c34)

真机信息
![image](https://github.com/youzan/vant-weapp/assets/110774929/69b56260-0868-48b0-90e2-0e7f0209f4ee)

### 重现步骤

真机调试

**Comment by lonffreytu** [comment]
看了源码，大概找到原因了。这样的实现方式着实让人难以理解。

```css
.van-stepper__minus:before,
.van-stepper__plus:before {
  height: 1px;
  width: 9px
}

.van-stepper__minus:after,
.van-stepper__plus:after {
  height: 9px;
  width: 1px
}

.van-stepper__minus:empty.van-stepper__minus:after,
.van-stepper__minus:empty.van-stepper__minus:before,
.van-stepper__minus:empty.van-stepper__plus:after,
.van-stepper__minus:empty.van-stepper__plus:before,
.van-stepper__plus:empty.van-stepper__minus:after,
.van-stepper__plus:empty.van-stepper__minus:before,
.van-stepper__plus:empty.van-stepper__plus:after,
.van-stepper__plus:empty.van-stepper__plus:before {
  background-color: currentColor;
  bottom: 0;
  content: "";
  left: 0;
  margin: auto;
  position: absolute;
  right: 0;
  top: 0
}
```

通过以上css代码可以知晓加减号分别是由`van-stepper__plus`和`van-stepper__minus` 的before和after实现的。before是横，after是竖（通过定义他们的高和宽实现的）。真机中不显示的原因是因为真机上不兼容`background-color: currentColor;`，即加减号的颜色是before和after的背景色，背景色又是跟前景色一样（currentColor）。但很可惜小程序不兼容CSS3中的`currentColor`。
解决办法
修改为直接作用在背景色，而不是前景色上

```css
.van-stepper__minus:empty.van-stepper__minus:after,
.van-stepper__minus:empty.van-stepper__minus:before,
.van-stepper__minus:empty.van-stepper__plus:after,
.van-stepper__minus:empty.van-stepper__plus:before,
.van-stepper__plus:empty.van-stepper__minus:after,
.van-stepper__plus:empty.van-stepper__minus:before,
.van-stepper__plus:empty.van-stepper__plus:after,
.van-stepper__plus:empty.van-stepper__plus:before {
  background-color: var(--stepper-button-icon-color, #323233);
  bottom: 0;
  content: "";
  left: 0;
  margin: auto;
  position: absolute;
  right: 0;
  top: 0
}

/* 禁用时的颜色 */
.van-stepper__minus--disabled.van-stepper__minus:empty.van-stepper__minus:before,
.van-stepper__plus--disabled.van-stepper__plus:empty.van-stepper__plus:before, 
.van-stepper__plus--disabled.van-stepper__plus:empty.van-stepper__plus:after {
  background-color: var(--stepper-button-disabled-icon-color, #c8c9cc)
}
```

希望官方能解决一下这个bug
