### ISSUE TITLE
[Bug Report] `van-image` 底部多出 4px

### ISSUE THREAD

**Issue by GF-Huang** [youzan/vant-weapp#5886]
### 重现链接

```xml
<view class="order-list-container">
  <view class="order-list-item round-border" wx:for="{{orders}}" wx:key="*this">
    <van-image src="随便一张图片" fit="fill" radius="10rpx" custom-class="order-img" />
  </view>
</view>
```
```css
.order-list-container {
  display: flex;
  flex-direction: column;
  gap: 20rpx;
  padding: 20rpx;
}

.order-list-item {
  padding: 20rpx;
  background-color: white;
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 20rpx;
}

.order-img {
  width: 200rpx;
  height: 200rpx;
}

.round-border {
  border-radius: 10rpx;
  overflow: hidden;
}
```

### Vant Weapp 版本

1.11.6

### 描述一下你遇到的问题。

图片下方多了4px空白。

![image](https://github.com/user-attachments/assets/dda1f17c-a5fd-41a5-aa78-9ae0f048af3f)
![image](https://github.com/user-attachments/assets/54f25845-d8fe-4fc0-a1b3-1df3d95b4156)

里面的 shadow-root 是正常的，不知道为什么。

![image](https://github.com/user-attachments/assets/3f239afd-9fcf-4642-b183-c5f8ff3982a4)

### 重现步骤

如上所述。

### 设备/浏览器

微信开发者工具1.06.2407120 和 iOS 真机
