### ISSUE TITLE
建议移除无用的 css prefix 

### ISSUE THREAD

**Issue by Airkro** [youzan/vant-weapp#659]
**描述一下问题**
组件库里面，很多这样的prefix是没有意义的。
```css
view {
  display: -webkit-box;
  display: -webkit-flex;
  display: flex;
}
```

依照[微信小程序官方文档](https://developers.weixin.qq.com/miniprogram/dev/framework/details.html)，其实可以将browserslist设置为
```
[development]
Chrome >= 60

[production]
Chrome >= 53
ChromeAndroid >= 53
iOS >= 8
```

为什么建议修改？
保留多余的prefix的话，会使得特定情况下难以覆盖组件样式，例如想在上述的例子中覆盖display属性

**环境**
- Vant Weapp 版本: 0.3.4
