### ISSUE TITLE
组件样式覆盖无效

### ISSUE THREAD

**Issue by jackie-cheng** [youzan/vant-weapp#710]
vant组件样式不可以更改吗，是小程序的机制吗？比如 .van-tabbar-item--active{color:#666}，我层级嵌套了三四层，发现active样式还是覆盖不掉，改一个color都改不掉。主题色也改不了吗？

**Comment by rex-zsd** [comment]
通过custom-class是可以修改的，参考
```html
<van-tabs custom-class="custom-class">
  <van-tab title="标签 1">内容 1</van-tab>
  <van-tab title="标签 2">内容 2</van-tab>
</van-tabs>
```
```css
.custom-class {
  van-tabs__line {
    background-color: blue !important;
  }

  .van-tab--active {
    color: blue !important;
  }
}
```
