### ISSUE TITLE
多行省略号样式的错误

### ISSUE THREAD

**Issue by weihongyu12** [youzan/vant-weapp#808]
**描述一下问题**

在使用多行省略号样式时，无法生效。

经查样式代码如下，缺少了`-webkit-box-orient: vertical`这个样式，导致多行省略号无法生效。

```css
/* vant-weapp/common/index.wxss */
van-multi-ellipsis--l2 {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
}
```

通过源代码的查阅，源代码拥有该样式，但是在编译后，该样式丢失

目前可以**确定该样式丢失是PostCSS方面的问题**

```less
/* packages/common/style/mixins */
.multi-ellipsis(@lines) {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: @lines;
  -webkit-box-orient: vertical;
}
```

**截图**

![image](https://user-images.githubusercontent.com/19792747/47437489-488fe680-d7db-11e8-95d3-5f4efca9b6ea.png)

**环境**
 - 设备: iPhone 7
 - 基础库版本: 2.3.0
 - Vant Weapp 版本: 0.4.2
