### ISSUE TITLE
安卓下 Tab的横向滚动会触发 默认的scrollBar？

### ISSUE THREAD

**Issue by casyalex** [youzan/vant-weapp#938]
注意：请按照下面的模板来新建 issue，不规范的 issue 会被立即关闭.

**描述一下问题**
貌似只有安卓下才会这样，有没办法屏蔽，不好看。

**截图**
![image](https://user-images.githubusercontent.com/5988630/48938866-6fae1500-ef4d-11e8-8437-d959ebc4f303.png)

**环境**
 - 设备: 只测试安卓8
 - 基础库版本: 2.0.0
 - Vant Weapp 版本:0.4.6

**Comment by rex-zsd** [comment]
用小米尝试了一下没复现。
可以参考一下社区的[回答](https://developers.weixin.qq.com/community/develop/doc/000e4e4b67c5806322079a0425b800?highLine=%25E9%259A%2590%25E8%2597%258Fscroll-view%25E6%25BB%259A%25E5%258A%25A8%25E6%259D%25A1)
在页面的wxss上增加
```css
::-webkit-scrollbar{
  width: 0;
  height: 0;
  color: transparent;
  display:none;
}
```
我们组件里没法加，加了会报错。
